/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as mainProductsRouteImport } from './routes/(main)/products'
import { Route as mainAboutRouteImport } from './routes/(main)/about'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProductsRoute = mainProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutRoute = mainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof mainAboutRoute
  '/products': typeof mainProductsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/': typeof mainIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof mainAboutRoute
  '/products': typeof mainProductsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/': typeof mainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/about': typeof mainAboutRoute
  '/(main)/products': typeof mainProductsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/(main)/': typeof mainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/products' | '/blogs/$slug' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/products' | '/blogs/$slug' | '/'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/about'
    | '/(main)/products'
    | '/blogs/$slug'
    | '/(main)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  BlogsSlugRoute: typeof BlogsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/products': {
      id: '/(main)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof mainProductsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about': {
      id: '/(main)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainAboutRoute: typeof mainAboutRoute
  mainProductsRoute: typeof mainProductsRoute
  mainIndexRoute: typeof mainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAboutRoute: mainAboutRoute,
  mainProductsRoute: mainProductsRoute,
  mainIndexRoute: mainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  BlogsSlugRoute: BlogsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
